# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='chat',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Chat'),
        ),
    ]
