# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_connections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connections',
            new_name='Connected',
        ),
    ]
