# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 22:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0005_connected_linked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connected',
            unique_together=set([('sender', 'addressee')]),
        ),
    ]
